#version: '3.8'
#
#services:
#  app:
#    build: .
#    container_name: app-container
#    ports:
#      - "8080:8080"
#    depends_on:
#      db:
#        condition: service_healthy
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-container:3306/anuncioss
#      SPRING_DATASOURCE_USERNAME: root
#      SPRING_DATASOURCE_PASSWORD: ""
#
#  db:
#    image: mysql:8.0
#    container_name: mysql-container
#    restart: always
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_DATABASE: anuncioss
#    ports:
#      - "3306:3306"
#    volumes:
#      - anuncioss:/var/lib/mysql
#    healthcheck:
#      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
#      interval: 10s
#      timeout: 5s
#      retries: 3
#
#volumes:
#  anuncioss:
